"""Design activity network: engineering steps, their inputs, outputs and iteration loops.

Each activity lists the activities it needs (`after`, with what flows across the link), the external inputs
it needs from outside the design team, the data files it owns (`writes`), the code that implements it
(`code`, used to check the map against the build) and the deliverables it issues (`docs`, document-number
prefixes). `FEEDBACK` holds the iteration loops: a later result that revises an earlier step.

Status: "done" = issued in this package at FEED level; "partial" = issued, but on simplified or assumed
input that must be replaced; "open" = not in this package, needed before detailed design / construction.
"""
from __future__ import annotations

DISCIPLINES = ["Project", "Process", "Safety", "Mechanical", "Layout", "Piping", "Civil", "I&C", "Electrical", "Cost"]


def A(id, name, disc, status, after=(), ext=(), writes=(), code=(), docs=(), note=""):
    return dict(id=id, name=name, disc=disc, status=status, after=list(after), ext=list(ext), writes=list(writes),
                code=list(code), docs=list(docs), note=note)


ACTIVITIES = [
    # ---------------------------------------------------------------- basis
    A("PRJ-01", "Design basis (BOD)", "Project", "done",
      ext=["Owner capacity, crude slate, product specs, turndown", "Site, climate and utility conditions",
           "Codes, standards and owner specifications"],
      code=["cfu/basis.py"], docs=["CFU-000-PR-BOD"],
      note="Every other activity reads the basis; a change here re-opens the whole package."),
    A("PRJ-02", "Crude assay characterisation", "Process", "partial",
      after=[("PRJ-01", "crude slate, design and check crudes")],
      ext=["Full laboratory assay (TBP, gravity, sulphur, salts, metals, acidity)"],
      code=["cfu/assay.py", "cfu/thermo.py"],
      note="Uses a published Arab Light assay with pseudo-components, not a lab assay."),
    A("PRC-00", "Rigorous simulation and model calibration", "Process", "open",
      after=[("PRJ-02", "lab assay pseudo-components")],
      ext=["Simulator licence (HYSYS / Petro-SIM / Pro-II)", "Licensor or owner operating data"],
      note="Replaces the ideal-VLE shortcut model; expect 5-10 C changes in draw temperatures."),
    # ---------------------------------------------------------------- process
    A("PRC-01", "Heat and material balance", "Process", "partial",
      after=[("PRJ-01", "capacity, product specs, utility conditions"), ("PRJ-02", "pseudo-components"),
             ("PRC-00", "calibrated cut points and efficiencies")],
      writes=["streams.json", "process_results.json"], code=["cfu/hmb.py", "cfu/export.py"],
      docs=["CFU-000-PR-HMB"]),
    A("PRC-02", "Process equipment sizing", "Process", "done",
      after=[("PRC-01", "flows, duties, column vapour/liquid loads")],
      writes=["equipment.json"], code=["cfu/sizing.py"], docs=["CFU-000-ME-LST"],
      note="Equipment list is the hub: mechanical, layout, electrical, I&C and cost all read it."),
    A("PRC-03", "Relief load and PSV sizing (unit)", "Process", "done",
      after=[("PRC-01", "relief compositions and rates"), ("PRC-02", "design pressures, wetted areas")],
      writes=["psv.json"], code=[], docs=[]),
    A("PRC-04", "Control loops and SIF definition", "Process", "done",
      after=[("PRC-01", "operating points"), ("PRC-02", "equipment and instrument ranges")],
      writes=["control_loops.json"], code=["cfu/control_loops.py"]),
    A("PRC-05", "Block flow diagram", "Process", "done",
      after=[("PRC-01", "unit yields")], code=["cfu/drawing/bfd.py"], docs=["CFU-000-PR-BFD"]),
    A("PRC-06", "Process flow diagrams", "Process", "done",
      after=[("PRC-01", "stream table"), ("PRC-02", "equipment data"), ("PRC-04", "principal control loops")],
      code=["cfu/pid/pfd.py"], docs=["CFU-000-PR-PFD", "CFU-100-PR-PFD", "CFU-200-PR-PFD"]),
    A("PRC-07", "Process design report", "Process", "done",
      after=[("PRC-01", "H&MB"), ("PRC-02", "sizing results"), ("PRC-03", "relief summary")],
      code=["cfu/reports.py"], docs=["CFU-000-PR-RPT-001"]),
    A("PIP-01", "Piping material classes", "Piping", "done",
      after=[("PRJ-01", "codes, corrosion basis"), ("PRC-01", "design T/P, sulphur and acid corrosion")],
      docs=["CFU-000-PI-SPC"], note="Defined in CONVENTIONS.md; summary issued with the P&IDs."),
    A("PRC-08", "P&IDs, line list, instrument index", "Process", "done",
      after=[("PRC-02", "equipment and design conditions"), ("PRC-03", "PSV tags and sizes"),
             ("PRC-04", "control loops and SIFs"), ("PRC-06", "PFD topology"), ("PIP-01", "piping classes"),
             ("LAY-01", "fire and gas detector locations")],
      writes=["lines.json", "instruments.json"],
      code=["cfu/pid/pid.py", "cfu/pid/pid_data.py", "cfu/pid/pid_symbols.py", "cfu/pid/symbols.py"],
      docs=["CFU-000-PR-PID", "CFU-100-PR-PID", "CFU-200-PR-PID", "CFU-900-PR-PID", "CFU-000-PI-LL",
            "CFU-000-IC-IDX"],
      note="Line list and instrument index feed piping, I&C and electrical; P&ID revisions ripple widely."),
    # ---------------------------------------------------------------- safety
    A("SAF-01", "Preliminary HAZOP", "Safety", "done",
      after=[("PRC-08", "P&IDs"), ("PRC-04", "SIFs"), ("PRC-03", "relief devices")],
      code=["cfu/wrapup/hazop.py"], docs=["CFU-000-PR-RPT-002"]),
    A("SAF-02", "Global flare load study", "Safety", "open",
      after=[("PRC-03", "unit relief loads")], ext=["Refinery flare network model, other units' loads"],
      note="Governing case (C-101 reflux failure, about 220 t/h) needs power and cooling-water failure cases."),
    A("SAF-03", "Formal HAZOP and LOPA workshop", "Safety", "open",
      after=[("PRC-08", "IFD P&IDs"), ("SAF-01", "preliminary findings"), ("ICS-02", "draft SIL targets")],
      ext=["Multidisciplinary team incl. owner operations"]),
    A("SAF-04", "Siting study, QRA, F&G mapping", "Safety", "open",
      after=[("LAY-01", "plot plan"), ("SAF-01", "major hazards"), ("ELE-02", "release sources")],
      ext=["Occupied building list, meteorology"],
      note="API 752/753 siting, QRA, fire and gas mapping and fireproofing; may move buildings or equipment."),
    # ---------------------------------------------------------------- mechanical
    A("MEC-01", "Mechanical design calculations", "Mechanical", "done",
      after=[("PRC-02", "design P/T, dimensions, internals"), ("PRC-01", "nozzle flows"), ("PRC-03", "PSV set points")],
      writes=["mech.json"],
      code=["cfu/mech/calc.py", "cfu/mech/vessel.py", "cfu/mech/heaters.py", "cfu/mech/hx.py", "cfu/mech/pumps.py",
            "cfu/mech/geometry.py", "cfu/mech/issues.py", "cfu/mech/report.py"],
      docs=["CFU-000-ME-CAL"]),
    A("MEC-02", "Equipment datasheets", "Mechanical", "done",
      after=[("MEC-01", "thicknesses, weights, nozzles"), ("PRC-02", "process data"), ("PRC-03", "PSV data")],
      code=["cfu/mech/datasheets.py", "cfu/mech/dsrender.py"], docs=["CFU-000-ME-DS"]),
    A("MEC-03", "Equipment GA drawings", "Mechanical", "done",
      after=[("MEC-01", "geometry, nozzle schedule")],
      code=["cfu/mech/ga_columns.py", "cfu/mech/ga_heaters.py", "cfu/mech/ga_misc.py", "cfu/mech/draw.py"],
      docs=["CFU-100-ME-GA", "CFU-200-ME-GA"]),
    A("VEN-01", "Vendor enquiries and vendor data", "Mechanical", "open",
      after=[("MEC-02", "datasheets for enquiry")],
      ext=["Vendor quotations and certified data (heaters, desalters, packing, pumps, ejectors, air coolers)"],
      note="Vendor data revises weights, nozzles, motor ratings and I/O; plan for one full update cycle."),
    # ---------------------------------------------------------------- layout
    A("LAY-01", "Plot plan and equipment layout", "Layout", "done",
      after=[("PRC-02", "equipment list and footprints"), ("PRC-01", "hazard inventory, heater duties"),
             ("PRJ-01", "site, spacing standards")],
      writes=["layout.json"], code=["cfu/layout/model.py", "cfu/layout/plotplan.py", "cfu/layout/__init__.py"],
      docs=["CFU-000-PL-PLT"]),
    A("LAY-02", "Sections and 3D layout model", "Layout", "done",
      after=[("LAY-01", "equipment positions, structures"), ("PRC-02", "equipment heights")],
      code=["cfu/layout/elevations.py", "cfu/layout/model3d.py"], docs=["CFU-000-PL-ELV", "CFU-000-PL-3DM"]),
    A("LAY-03", "3D model reviews and constructability", "Layout", "open",
      after=[("PIP-02", "routed model"), ("LAY-02", "layout model"), ("CIV-01", "structures")],
      ext=["Owner operations and maintenance reviewers"], note="30/60/90 % model reviews."),
    # ---------------------------------------------------------------- piping
    A("PIP-02", "Piping routing and 3D model", "Piping", "done",
      after=[("PRC-08", "line list, in-line instruments"), ("LAY-01", "nozzle positions, pipe rack"),
             ("PRC-03", "PSV inlet/outlet"), ("MEC-01", "nozzle sizes, weights")],
      writes=["routing.json"],
      code=["cfu/piping/router.py", "cfu/piping/auto.py", "cfu/piping/critical.py", "cfu/piping/model.py",
            "cfu/piping/glb.py", "cfu/piping/export.py", "cfu/piping/specs.py", "cfu/piping/__init__.py"],
      docs=["CFU-000-PI-3DM"]),
    A("PIP-03", "Pipe stress and supports (screening)", "Piping", "partial",
      after=[("PIP-02", "routed geometry"), ("MEC-01", "nozzle allowables")],
      code=["cfu/piping/stress.py", "cfu/piping/report.py"], docs=["CFU-000-PI-RPT"],
      note="Screening only; CAESAR II analysis is PIP-05."),
    A("PIP-04", "Isometrics and piping MTO", "Piping", "done",
      after=[("PIP-02", "routed geometry"), ("PIP-01", "piping classes")],
      code=["cfu/piping/iso.py", "cfu/piping/mto.py"],
      docs=["CFU-000-PI-ISO", "CFU-100-PI-ISO", "CFU-200-PI-ISO", "CFU-000-PI-MTO"]),
    A("PIP-05", "Detailed pipe stress (CAESAR II)", "Piping", "open",
      after=[("PIP-03", "critical line list"), ("VEN-01", "certified nozzle allowables")],
      ext=["CAESAR II or equivalent"], note="Includes nozzle-load agreement with equipment vendors."),
    # ---------------------------------------------------------------- civil
    A("CIV-01", "Geotechnical, civil and structural design", "Civil", "open",
      after=[("LAY-01", "plot plan"), ("MEC-01", "operating and test weights"), ("PIP-03", "support loads")],
      ext=["Geotechnical survey", "Topographic survey"],
      note="No civil deliverables in this package: foundations, pipe rack and structures are still to do."),
    # ---------------------------------------------------------------- I&C
    A("ICS-01", "Control philosophy and schemes", "I&C", "done",
      after=[("PRC-04", "loops and SIFs"), ("PRC-01", "operating points"), ("PRC-02", "equipment")],
      code=["cfu/ic/csd.py", "cfu/ic/report.py"],
      docs=["CFU-000-IC-RPT-001", "CFU-000-IC-CSD", "CFU-100-IC-CSD", "CFU-200-IC-CSD"]),
    A("ICS-02", "SIF list and SIL determination (LOPA)", "I&C", "partial",
      after=[("PRC-04", "SIF definitions"), ("SAF-01", "hazard scenarios")],
      docs=["CFU-000-IC-RPT-002"], note="LOPA frequencies are FEED judgements pending SAF-03."),
    A("ICS-03", "Cause and effect matrix", "I&C", "done",
      after=[("PRC-04", "SIFs"), ("PRC-03", "relief devices"), ("PRC-02", "equipment"), ("ICS-02", "SIL targets")],
      code=["cfu/ic/ce.py"], docs=["CFU-000-IC-CE"]),
    A("ICS-04", "Control valve sizing", "I&C", "done",
      after=[("PRC-01", "flows, densities"), ("PRC-02", "pump curves"), ("PRC-04", "valve tags"),
             ("PRC-08", "line sizes")],
      code=["cfu/ic/cvsizing.py"], docs=["CFU-000-IC-CAL"]),
    A("ICS-05", "I/O list", "I&C", "done",
      after=[("PRC-08", "instrument index"), ("PRC-04", "loops and SIFs"), ("PRC-02", "motor drivers"),
             ("LAY-01", "junction-box zones")],
      writes=["io_list.json"], code=["cfu/ic/iolist.py"], docs=["CFU-000-IC-IOL"]),
    A("ICS-06", "Loop diagrams", "I&C", "done",
      after=[("ICS-05", "terminations, cabinets")], code=["cfu/ic/loops_ld.py"], docs=["CFU-100-IC-LD"]),
    A("ICS-07", "ICS architecture", "I&C", "done",
      after=[("ICS-05", "I/O counts"), ("ELE-03", "UPS feeds")], code=["cfu/ic/arch.py"], docs=["CFU-000-IC-BLK"]),
    A("ICS-08", "SIL verification and SRS", "I&C", "open",
      after=[("ICS-02", "SIL targets"), ("SAF-03", "validated LOPA"), ("VEN-01", "device failure data")],
      note="PFDavg calculations and the safety requirements specification (IEC 61511)."),
    # ---------------------------------------------------------------- electrical
    A("ELE-01", "Electrical load list", "Electrical", "done",
      after=[("PRC-02", "motor ratings, absorbed power")], code=["cfu/elec/loads.py"], docs=["CFU-000-EL-LDL"]),
    A("ELE-02", "Hazardous area classification", "Electrical", "done",
      after=[("LAY-01", "release-source positions"), ("PRC-02", "fluids and conditions"),
             ("PRC-04", "analysers and vents")],
      code=["cfu/elec/hac.py"], docs=["CFU-000-EL-HAC"]),
    A("ELE-03", "Electrical sizing, single-line diagrams", "Electrical", "done",
      after=[("ELE-01", "loads and demand")], writes=["electrical.json"],
      code=["cfu/elec/study.py", "cfu/elec/sld.py", "cfu/elec/symbols.py", "cfu/elec/reports.py"],
      docs=["CFU-000-EL-SLD", "CFU-000-EL-CAL"]),
    A("ELE-04", "Cable schedule", "Electrical", "done",
      after=[("ELE-01", "loads"), ("ELE-03", "feeders"), ("LAY-01", "routes"), ("ELE-02", "zone ratings")],
      code=["cfu/elec/cables.py", "cfu/elec/__init__.py"], docs=["CFU-000-EL-CBL"]),
    A("ELE-05", "Power system studies and protection", "Electrical", "open",
      after=[("ELE-03", "SLD"), ("VEN-01", "motor and transformer data")],
      ext=["Utility short-circuit data", "ETAP or equivalent"],
      note="Load flow, short circuit, motor starting, arc flash, relay coordination."),
    # ---------------------------------------------------------------- cost & close-out
    A("CST-01", "Class 4 cost estimate", "Cost", "done",
      after=[("PRC-02", "equipment list"), ("MEC-01", "shell weights")],
      code=["cfu/wrapup/estimate.py"], docs=["CFU-000-PM-EST"]),
    A("CST-02", "Class 3 cost estimate", "Cost", "open",
      after=[("CST-01", "estimate structure"), ("VEN-01", "budget quotes"), ("PIP-04", "piping MTO"),
             ("ELE-04", "cable quantities"), ("CIV-01", "civil quantities")]),
    A("PRJ-03", "Document register and portal", "Project", "done",
      after=[("CST-01", "estimate"), ("SAF-01", "HAZOP"), ("PIP-04", "isometrics"), ("ICS-06", "loop diagrams"),
             ("ICS-07", "architecture"), ("ELE-04", "cables"), ("MEC-03", "GAs"), ("LAY-02", "3D model"),
             ("PRC-05", "BFD"), ("PRC-07", "process report"), ("ICS-01", "control philosophy"),
             ("ICS-03", "C&E"), ("ICS-04", "CV sizing"), ("MEC-02", "datasheets"), ("PIP-03", "stress study")],
      code=["cfu/wrapup/portal.py", "cfu/wrapup/__init__.py", "cfu/wrapup/phases.py"], docs=["CFU-000-PM-REG", "CFU-000-PM-DEP"]),
    A("PRJ-04", "PE review, seal and IFC issue", "Project", "open",
      after=[("PRJ-03", "complete document set"), ("SAF-03", "closed HAZOP actions"), ("ICS-08", "SIL verification"),
             ("PIP-05", "stress sign-off"), ("ELE-05", "studies"), ("CST-02", "Class 3 estimate"),
             ("LAY-03", "model review"), ("SAF-04", "siting study"), ("SAF-02", "flare study")],
      ext=["Licensed Professional Engineer in responsible charge"],
      note="Nothing in this package is sealed; this is the gate before any use for construction."),
]

# Iteration loops: (from, to, what is revised). A later result revises an earlier activity.
FEEDBACK = [
    ("MEC-01", "PRC-02", "mechanical holds re-rate sizing (C-201 bed-1 diameter, heater box length)"),
    ("MEC-01", "LAY-01", "calculated dimensions and weights update footprints and spacing"),
    ("PIP-02", "PRC-02", "routed lengths update pump and line hydraulics"),
    ("PIP-02", "LAY-01", "rack width and clashes move equipment"),
    ("ICS-04", "PRC-08", "control valve sizes and reducers shown on the P&IDs"),
    ("SAF-01", "PRC-08", "HAZOP recommendations revise the P&IDs"),
    ("ELE-04", "ELE-03", "actual cable impedances re-run the motor-starting voltage-dip check"),
    ("ICS-07", "ELE-01", "ICS cabinet and UPS loads added to the load list"),
    ("SAF-02", "PRC-03", "flare back-pressure changes PSV type and size"),
    ("SAF-03", "PRC-08", "formal HAZOP actions revise the P&IDs"),
    ("SAF-04", "LAY-01", "siting study moves occupied buildings and equipment"),
    ("VEN-01", "MEC-01", "certified vendor dimensions, weights and nozzles"),
    ("VEN-01", "LAY-01", "vendor package footprints"),
    ("VEN-01", "ELE-01", "certified motor ratings"),
    ("VEN-01", "ICS-05", "vendor package I/O"),
]

# Helpers that load data on behalf of their caller (reads are attributed to the calling module).
HELPERS = {"cfu/mech/common.py", "cfu/ic/common.py", "cfu/elec/common.py", "cfu/export.py", "cfu/docgen.py",
           "cfu/drawing/sheet.py", "cfu/wrapup/depmap.py", "cfu/wrapup/activities.py"}
